# Generated by Django 5.2.7 on 2025-10-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('binarySwitch', 'Binary Switch'), ('dimmableLight', 'Dimmable Light')], default='binarySwitch', max_length=20),
        ),
    ]
